name: 猎取订阅

on:
  workflow_dispatch:
  
  schedule:
    - cron: '0 12 10,20,1 * *'

jobs:
  fetch-website-content:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码库
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: 安装依赖
        run: |
          npm install puppeteer-core
          npm install moment
          npm install base64-js
          npm install p-queue

      - name: 检查结果目录
        run: |         
          if [ ! -d "bata" ]; then
            mkdir bata
          fi
          
      - name: 延时
        run: |
          delay=$((RANDOM % 9 + 1))
          sleep "$delay"
        
      - name: 读取订阅
        env:
          TZ: 'Asia/Shanghai'
        run: |
          node readII_website.js
        
      - name: 清除 bata 目录
        run: |
          find bata/ -type f -exec rm {} +
          
      - name: 拉取远程更改
        run: git pull origin master


      - name: 设置 Git 配置
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: 提交文件到主分支
        continue-on-error: true
        run: |
          git add .
          git commit -m "Add website content"
          git push
