name: 读取订阅

on:
  workflow_dispatch:
  
  schedule:
    - cron: '0 12 */7 * *'

jobs:
  fetch-website-content:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码库
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: 安装依赖
        run: |
          npm install puppeteer-core
          npm install moment
          npm install base64-js

      - name: 检查结果目录
        run: |
          if [ ! -d "data" ]; then
            mkdir data
          fi
          if [ ! -d "result" ]; then
            mkdir result
          fi
          if [ ! -d "share" ]; then
            mkdir share
          fi
      
      - name: 延时
        run: |
          delay=$((RANDOM % 9 + 1))
          sleep "$delay"

      - name: 读取订阅
        env:
          TZ: 'Asia/Shanghai'
        run: |
          node read_website.js

      - name: 调用转换脚本
        run: |
          python convert.py

      - name: 更新 README.md
        run: |
          if [[ -f README.md ]]; then
            # 读取当前时间
            timestamp=$(TZ='Asia/Shanghai' date '+%A %Y年%m月%d日 %T')
            # 创建临时文件
            echo "### 更新：$timestamp" > README.md.tmp
            # 将新的内容追加到临时文件中
            cat README.md >> README.md.tmp
            # 替换原始 README.md 文件
            mv README.md.tmp README.md
          fi

      - name: 清除 data 目录
        run: |
          find data/ -type f -exec rm {} +

      - name: 设置 Git 配置
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: 提交文件到主分支
        continue-on-error: true
        run: |
          git add .
          git commit -m "Add website content"
          git push
