name: 搜索订阅

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 */10 * *'

jobs:
  extract_urls:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4
        pip install requests

    - name: Extract URLs from Search
      id: search
      run: |
        declare -a search_queries=("节点订阅" "节点池2023" "VEMSS节点订阅")
        for query in "${search_queries[@]}"; do
          echo "Searching for: $query"
          python extract_urls.py "$query"
        done

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add furls
        git commit -m "Add extracted URLs"
        git push
