name: Extract URLs from Search

on:
  workflow_dispatch:
  schedule:
    - cron: '* * */10 * *'

jobs:
  extract_urls:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4
        pip install requests

    - name: Extract URLs from Google Search
      id: search
      run: |
        python extract_urls.py
      env:
        SEARCH_QUERY: "订阅节点"

    - name: Save URLs to file
      run: |
        if [[ -s urls ]]; then
          echo "Search completed. Saving URLs to file."
          cat urls >> urls_temp
          mv urls_temp urls
        else
          echo "Search timed out or no URLs found. Generating empty urls file."
          touch urls
        fi

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add urls
        git commit -m "Add extracted URLs"
        git push
